import { ClerkProvider } from "@clerk/nextjs";
import {Outfit} from "next/font/google"
import { Metadata } from "next";
import "./globals.css";


const outfit = Outfit({subsets:["latin"]})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={outfit.className}>
          {/* Check if user is authenticated */}
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
